[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  TZ = "America/New_York"

[dev]
  command = "bun run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
